apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-services
  namespace: saas-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-services
  template:
    metadata:
      labels:
        app: agent-services
    spec:
      containers:
      - name: agent-services
        image: saas-platform/agent-services:latest
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: openai-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: agent-services
  namespace: saas-platform
spec:
  selector:
    app: agent-services
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP
