apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: saas-platform
data:
  LOG_LEVEL: "INFO"
  ENABLE_MONITORING: "true"
  MAX_CONCURRENT_AGENTS: "10"

---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: saas-platform
type: Opaque
data:
  url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAbG9jYWxob3N0L3NhYXNfcGxhdGZvcm0=  # base64 encoded

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: saas-platform
type: Opaque
data:
  url: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OQ==  # base64 encoded

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
  namespace: saas-platform
type: Opaque
data:
  openai-key: eW91ci1vcGVuYWkta2V5LWhlcmU=  # base64 encoded
  anthropic-key: eW91ci1hbnRocm9waWMta2V5LWhlcmU=  # base64 encoded
