name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        run: npm run build
        env:
          NODE_ENV: production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push production images
        run: |
          # Frontend
          docker build -t ghcr.io/${{ github.repository }}/frontend:${{ github.ref_name }} ./apps/frontend
          docker push ghcr.io/${{ github.repository }}/frontend:${{ github.ref_name }}
          
          # Backend
          docker build -t ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }} ./apps/backend
          docker push ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }}

      # Add your deployment steps here (e.g., kubectl, helm, terraform)
      - name: Deploy to Kubernetes
        run: |
          echo "Add your Kubernetes deployment commands here"
          # kubectl set image deployment/frontend frontend=ghcr.io/${{ github.repository }}/frontend:${{ github.ref_name }}
          # kubectl set image deployment/backend backend=ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }}
